trigger:
- '*'

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

# variables:
#   # Define your Azure Service Principal credentials as pipeline variables
#   SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
#   CLIENT_ID: $(CLIENT_ID)
#   CLIENT_SECRET: $(CLIENT_SECRET) # Define this variable as a secret variable in your pipeline settings
#   TENANT_ID: $(TENANT_ID)

steps:
- script: |
    echo "Installing Terraform..."
    curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
    sudo apt-get update && sudo apt-get install terraform
    echo "Terraform installed."
  displayName: 'Install Terraform'

- script: |
    echo "Terraform Init..."
    terraform init -var "ARM_ACCESS_KEY=$(ARM_ACCESS_KEY)""
    echo "Terraform Init complete."
  displayName: 'Terraform Init'

- script: |
    terraform plan -var "client_id=$(CLIENT_ID)" -var "client_secret=$(CLIENT_SECRET)" -var "tenant_id=$(TENANT_ID)" -var "subscription_id=$(SUBSCRIPTION_ID)"
  displayName: 'Terraform plan'

- script: |
    terraform apply --auto-approve -var "client_id=$(CLIENT_ID)" -var "client_secret=$(CLIENT_SECRET)" -var "tenant_id=$(TENANT_ID)" -var "subscription_id=$(SUBSCRIPTION_ID)"
  displayName: 'Terraform Apply'